//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IzendaCMS.Classes
{
    using System.Collections.Generic;

    public partial class CourseGrade
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public CourseGrade()
        {
            this.Student_CourseGrades = new HashSet<Student_CourseGrades>();
        }
    
        public int Id { get; set; }
        public int CourseId { get; set; }
        public string FinalGrade { get; set; }
        
        public virtual Course Course { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Student_CourseGrades> Student_CourseGrades { get; set; }
    }
}
